on: 
  workflow_dispatch:
    inputs:
      enviroment:
        description: "choose enviroment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: rund deployment
        run: echo "Deploye the application"
